language: go

go:
  - 1.4.1
  
install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/tools/godep
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - godep go test -race -v ./...
  - godep go test -cover -v ./...
