language: go

go:
  - 1.2
  - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -d -v ./...
  - go get github.com/revel/cmd/revel

script:
  - revel test github.com/asm-products/firesize
