language: go

go:
  - 1.2
  - tip

install:
  - go install -race std
  - go get code.google.com/p/go.tools/cmd/cover
  - export PATH=$PATH:$HOME/gopath/bin  

script:
  - godep go test -race ./...
  - godep go test -cover ./...
